spring.application.name=ETimes

spring.datasource.url=jdbc:postgresql://ep-falling-unit-ad6nt4zf-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_myzNG3xWYb1R

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect